optimizer:
  _target_: torch.optim.Muon
  params: None
  lr: 1e-3
  weight_decay: 0.1
  momentum: 0.95
  nesterov: True
  ns_coefficients: (3.4445, -4.775, 2.0315)
  eps: 1e-07
  ns_steps: 5
  adjust_lr_fn: None